In [ ]:
import torch
import numpy as np

In [ ]:
x = torch.arange(6).reshape(3,2)
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [ ]:
x[1,1]

tensor(3)

In [ ]:
# Getting all the values from column 1

x[:,1]

tensor([1, 3, 5])

In [ ]:
x[:,1:]

tensor([[1],
        [3],
        [5]])

### Reshaping tensors with view

In [ ]:
x = torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x.reshape(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# view reflects the most current data

x = torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x.shape

torch.Size([10])

In [ ]:
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
z = x.view(2,5)
z

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
x[0] = 9999
x

tensor([9999,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [ ]:
z

tensor([[9999,    1,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [ ]:
# Put -1 if you dont know what the column size is. Python will figure that out for you
x.view(2,-1)

tensor([[9999,    1,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

### Tensor Arithmatic

In [ ]:
a = torch.tensor([1.,2.,3.])

In [ ]:
b = torch.tensor([4.,5.,6.])

In [ ]:
a + b

tensor([5., 7., 9.])

In [ ]:
torch.add(a,b)

tensor([5., 7., 9.])

In [ ]:
# Same thing as a * b
a.mul(b)

tensor([ 4., 10., 18.])

In [ ]:
a

tensor([1., 2., 3.])

In [ ]:
# Same thing as a = a * b

a.mul_(b)

tensor([ 4., 10., 18.])

In [ ]:
a

tensor([ 4., 10., 18.])

## Part 2:

In [ ]:
a = torch.tensor([1.,2.,3.])

In [ ]:
# dot product
a.dot(b)

tensor(32.)

In [ ]:
# 2D products

a = torch.tensor([[0,2,4],[1,3,5]])

In [ ]:
b = torch.tensor([[6,7],[8,9],[10,11]])

In [ ]:
# a*b won't work since the sizes dont match

torch.mm(a,b)

tensor([[56, 62],
        [80, 89]])

In [ ]:
a@b

tensor([[56, 62],
        [80, 89]])

In [ ]:
# Euclidian norm of a tensor

x = torch.tensor([2.,3.,4.,5.])
x

tensor([2., 3., 4., 5.])

In [ ]:
x.norm()

tensor(7.3485)

In [ ]:
# return num of elemnts
x.numel()

4

In [ ]:
len(x)

4

In [ ]:
# a is a 2 x 3 matrix
len(a)

2

In [ ]:
a.numel()

6