In [ ]:
import torch
import numpy as np

In [ ]:
torch.__version__

'1.5.0+cu101'

In [ ]:
arr = np.array([1,2,3,4,5])

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
x = torch.from_numpy(arr)
x

tensor([1, 2, 3, 4, 5])

In [ ]:
torch.as_tensor(arr)

tensor([1, 2, 3, 4, 5])

In [ ]:
type(x)

torch.Tensor

In [ ]:
x.dtype

torch.int64

### Let's try with a matrix

In [ ]:
arr2d = np.arange(0.0,12.0)
arr2d

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [ ]:
arr2d = arr2d.reshape(4,3)
arr2d

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [ ]:
x2 = torch.from_numpy(arr2d)
x2

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

### When you create a tensor from numpy arr. the tensor will change if numpy arr changes

In [ ]:
arr

array([1, 2, 3, 4, 5])

In [ ]:
arr[0] = 99

In [ ]:
x

tensor([99,  2,  3,  4,  5])

### If we don't want direct link between the tesnsor and np array, then do this

In [ ]:
my_arr = np.arange(0,10)
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Using torch.tensor creates a copy of the array, no the tensor and array are no longer directly linked
my_tensor = torch.tensor(my_arr)
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# This creates a tensor directly linked to my_arr
my_other_tensor = torch.from_numpy(my_arr)
my_other_tensor

tensor([9999,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [ ]:
my_arr[0] = 9999

In [ ]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_other_tensor

tensor([9999,    1,    2,    3,    4,    5,    6,    7,    8,    9])

## Summary: 
#### torch.from_numpy, torch.as_tensor(arr) creates direct link
####         torch.tensor(my_arr) creates a copy of array with no direct link

# <hr>
# <hr>

# Part 2:

### creating a tensor with lowercase t creates an int type tensor
### creating a tensor with uppercase T creates a float type tensor

In [ ]:
new_arr = np.array([1,2,3])

In [ ]:
new_arr.dtype

dtype('int64')

In [ ]:
# lowercase: int
torch.tensor(new_arr)

tensor([1, 2, 3])

In [ ]:
torch.tensor(new_arr).dtype

torch.int64

In [ ]:
# Uppercase: float
torch.Tensor(new_arr)

tensor([1., 2., 3.])

In [ ]:
torch.Tensor(new_arr).dtype

torch.float32

### Creating tensor from scratch

In [ ]:
# Creates a placeholder tensor. The numbers in a blank tensor means 0 or extremely small aka 0

torch.empty(2,2)

tensor([[4.5895e-36, 0.0000e+00],
        [1.5134e-43, 5.6052e-44]])

In [ ]:
# Creates new tensor with zeroes of int type

torch.zeros(4,3, dtype=torch.int64)


tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [ ]:
# Creates new tensor with 1s

torch.ones(4,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# Creates new tensor 1-D array and reshape them to 3x3 matrix

torch.arange(0,18,2).reshape(3,3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [ ]:
# Creates new tensor from a list

torch.tensor([1,2,3])

tensor([1, 2, 3])

In [ ]:
my_tensor = torch.tensor([1,2,3])
my_tensor.dtype

torch.int64

In [ ]:
# Change data type of tensor

my_tensor.type(torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
# Random numbers with tensor

# Creates a matrix with random float numbers between 0 to 1
torch.rand(4,3)

tensor([[0.1859, 0.1238, 0.9263],
        [0.9209, 0.8518, 0.5269],
        [0.9874, 0.2414, 0.1367],
        [0.1760, 0.5840, 0.6931]])

In [ ]:
# Creates a standard normal distribution of random numbers with mean 0 and std_dev 1

torch.randn(4,3)

tensor([[ 0.9319, -0.1993, -0.8698],
        [ 1.4431, -1.4743,  0.5781],
        [ 0.7736,  0.0147,  1.1039],
        [ 0.1264, -0.4537, -0.0631]])

In [ ]:
# Create your own custom random number matrix in tensor
# Numbers ranges from low to high-1

torch.randint(low=0, high=10, size=(5,5))

tensor([[6, 6, 1, 2, 0],
        [1, 8, 4, 2, 5],
        [8, 5, 6, 2, 8],
        [1, 2, 0, 2, 4],
        [9, 7, 7, 9, 3]])

In [ ]:
# Create your own custom random number matrix in tensor using a variable as shape

x = torch.zeros(2,5)
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [ ]:
x.shape

torch.Size([2, 5])

In [ ]:
# Creates a tensor matrix with random number between 0 and 1

torch.rand_like(x)

tensor([[0.8747, 0.3996, 0.3169, 0.4608, 0.1630],
        [0.5397, 0.0177, 0.3212, 0.7882, 0.5717]])

In [ ]:
# Creates a tensor matrix with normaly distributed numbers

torch.randn_like(x)

tensor([[ 0.8113, -0.0408,  0.4159,  0.3194,  0.1516],
        [ 0.4664,  0.3418, -0.3231, -0.2625,  0.3457]])

In [ ]:
# Create your own custom random number matrix in tensor with shape x

torch.randint_like(x, low=0, high=11)

tensor([[ 3.,  4.,  0.,  7.,  2.],
        [ 2.,  6.,  2., 10.,  4.]])

In [ ]:
# Specifying a manual seed with ensure the same random output every time
# NOTE: the random seed command and rand command need to be in the same cell
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])